function(yaff_apply_sanitizers target)
    if(NOT YAFF_SANITIZER OR YAFF_SANITIZER STREQUAL "none")
        return()
    endif()

    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        message(WARNING "YAFF_SANITIZER is set but compiler '${CMAKE_CXX_COMPILER_ID}' may not support -fsanitize. Skipping.")
        return()
    endif()

    if(YAFF_SANITIZER STREQUAL "asan")
        set(_sanitize_flags address)
    elseif(YAFF_SANITIZER STREQUAL "ubsan")
        set(_sanitize_flags undefined)
    elseif(YAFF_SANITIZER STREQUAL "asan,ubsan")
        set(_sanitize_flags address,undefined)
    else()
        message(FATAL_ERROR "Unknown YAFF_SANITIZER value '${YAFF_SANITIZER}'. Expected: none | asan | ubsan | asan,ubsan")
    endif()

    set(_flags -fsanitize=${_sanitize_flags} -fno-omit-frame-pointer)
    target_compile_options(${target} PRIVATE ${_flags})
    target_link_options   (${target} PRIVATE ${_flags})
endfunction()
