if(NOT YAFF_PROTO_IMPORT_DIR)
    file(REAL_PATH "${CMAKE_CURRENT_LIST_DIR}/../../.." _yaff_pkg_root)
    set(YAFF_PROTO_IMPORT_DIR "${_yaff_pkg_root}/include" CACHE PATH "Path to yaff proto import directory")
    unset(_yaff_pkg_root)
endif()

if(NOT TARGET yaff::protoc_plugin)
    if(CMAKE_CROSSCOMPILING)
        find_program(YAFF_PROTOC_GEN_YAFF_PROGRAM NAMES protoc-gen-yaff PATHS ENV PATH NO_DEFAULT_PATH)
    endif()
    if(NOT YAFF_PROTOC_GEN_YAFF_PROGRAM)
        find_program(YAFF_PROTOC_GEN_YAFF_PROGRAM NAMES protoc-gen-yaff)
    endif()
    if(NOT YAFF_PROTOC_GEN_YAFF_PROGRAM)
        set(YAFF_PROTOC_GEN_YAFF_PROGRAM "${CMAKE_CURRENT_LIST_DIR}/../../../bin/protoc-gen-yaff${CMAKE_EXECUTABLE_SUFFIX}")
    endif()
    get_filename_component(YAFF_PROTOC_GEN_YAFF_PROGRAM "${YAFF_PROTOC_GEN_YAFF_PROGRAM}" ABSOLUTE)

    add_executable(yaff::protoc_plugin IMPORTED)
    set_property(TARGET yaff::protoc_plugin PROPERTY IMPORTED_LOCATION "${YAFF_PROTOC_GEN_YAFF_PROGRAM}")
endif()
