syntax = "proto3";

package benchmark_serialize;

message Flat100 {
    uint64 v0 = 1;
    uint64 v1 = 2;
    uint64 v2 = 3;
    uint64 v3 = 4;
    uint64 v4 = 5;
    uint64 v5 = 6;
    uint64 v6 = 7;
    uint64 v7 = 8;
    uint64 v8 = 9;
    uint64 v9 = 10;
    uint64 v10 = 11;
    uint64 v11 = 12;
    uint64 v12 = 13;
    uint64 v13 = 14;
    uint64 v14 = 15;
    uint64 v15 = 16;
    uint64 v16 = 17;
    uint64 v17 = 18;
    uint64 v18 = 19;
    uint64 v19 = 20;
    uint64 v20 = 21;
    uint64 v21 = 22;
    uint64 v22 = 23;
    uint64 v23 = 24;
    uint64 v24 = 25;
    uint64 v25 = 26;
    uint64 v26 = 27;
    uint64 v27 = 28;
    uint64 v28 = 29;
    uint64 v29 = 30;
    uint64 v30 = 31;
    uint64 v31 = 32;
    uint64 v32 = 33;
    uint64 v33 = 34;
    uint64 v34 = 35;
    uint64 v35 = 36;
    uint64 v36 = 37;
    uint64 v37 = 38;
    uint64 v38 = 39;
    uint64 v39 = 40;
    uint64 v40 = 41;
    uint64 v41 = 42;
    uint64 v42 = 43;
    uint64 v43 = 44;
    uint64 v44 = 45;
    uint64 v45 = 46;
    uint64 v46 = 47;
    uint64 v47 = 48;
    uint64 v48 = 49;
    uint64 v49 = 50;
    uint64 v50 = 51;
    uint64 v51 = 52;
    uint64 v52 = 53;
    uint64 v53 = 54;
    uint64 v54 = 55;
    uint64 v55 = 56;
    uint64 v56 = 57;
    uint64 v57 = 58;
    uint64 v58 = 59;
    uint64 v59 = 60;
    uint64 v60 = 61;
    uint64 v61 = 62;
    uint64 v62 = 63;
    uint64 v63 = 64;
    uint64 v64 = 65;
    uint64 v65 = 66;
    uint64 v66 = 67;
    uint64 v67 = 68;
    uint64 v68 = 69;
    uint64 v69 = 70;
    uint64 v70 = 71;
    uint64 v71 = 72;
    uint64 v72 = 73;
    uint64 v73 = 74;
    uint64 v74 = 75;
    uint64 v75 = 76;
    uint64 v76 = 77;
    uint64 v77 = 78;
    uint64 v78 = 79;
    uint64 v79 = 80;
    uint64 v80 = 81;
    uint64 v81 = 82;
    uint64 v82 = 83;
    uint64 v83 = 84;
    uint64 v84 = 85;
    uint64 v85 = 86;
    uint64 v86 = 87;
    uint64 v87 = 88;
    uint64 v88 = 89;
    uint64 v89 = 90;
    uint64 v90 = 91;
    uint64 v91 = 92;
    uint64 v92 = 93;
    uint64 v93 = 94;
    uint64 v94 = 95;
    uint64 v95 = 96;
    uint64 v96 = 97;
    uint64 v97 = 98;
    uint64 v98 = 99;
    uint64 v99 = 100;
}

message Flat100E {
    optional uint64 v0 = 1;
    optional uint64 v1 = 2;
    optional uint64 v2 = 3;
    optional uint64 v3 = 4;
    optional uint64 v4 = 5;
    optional uint64 v5 = 6;
    optional uint64 v6 = 7;
    optional uint64 v7 = 8;
    optional uint64 v8 = 9;
    optional uint64 v9 = 10;
    optional uint64 v10 = 11;
    optional uint64 v11 = 12;
    optional uint64 v12 = 13;
    optional uint64 v13 = 14;
    optional uint64 v14 = 15;
    optional uint64 v15 = 16;
    optional uint64 v16 = 17;
    optional uint64 v17 = 18;
    optional uint64 v18 = 19;
    optional uint64 v19 = 20;
    optional uint64 v20 = 21;
    optional uint64 v21 = 22;
    optional uint64 v22 = 23;
    optional uint64 v23 = 24;
    optional uint64 v24 = 25;
    optional uint64 v25 = 26;
    optional uint64 v26 = 27;
    optional uint64 v27 = 28;
    optional uint64 v28 = 29;
    optional uint64 v29 = 30;
    optional uint64 v30 = 31;
    optional uint64 v31 = 32;
    optional uint64 v32 = 33;
    optional uint64 v33 = 34;
    optional uint64 v34 = 35;
    optional uint64 v35 = 36;
    optional uint64 v36 = 37;
    optional uint64 v37 = 38;
    optional uint64 v38 = 39;
    optional uint64 v39 = 40;
    optional uint64 v40 = 41;
    optional uint64 v41 = 42;
    optional uint64 v42 = 43;
    optional uint64 v43 = 44;
    optional uint64 v44 = 45;
    optional uint64 v45 = 46;
    optional uint64 v46 = 47;
    optional uint64 v47 = 48;
    optional uint64 v48 = 49;
    optional uint64 v49 = 50;
    optional uint64 v50 = 51;
    optional uint64 v51 = 52;
    optional uint64 v52 = 53;
    optional uint64 v53 = 54;
    optional uint64 v54 = 55;
    optional uint64 v55 = 56;
    optional uint64 v56 = 57;
    optional uint64 v57 = 58;
    optional uint64 v58 = 59;
    optional uint64 v59 = 60;
    optional uint64 v60 = 61;
    optional uint64 v61 = 62;
    optional uint64 v62 = 63;
    optional uint64 v63 = 64;
    optional uint64 v64 = 65;
    optional uint64 v65 = 66;
    optional uint64 v66 = 67;
    optional uint64 v67 = 68;
    optional uint64 v68 = 69;
    optional uint64 v69 = 70;
    optional uint64 v70 = 71;
    optional uint64 v71 = 72;
    optional uint64 v72 = 73;
    optional uint64 v73 = 74;
    optional uint64 v74 = 75;
    optional uint64 v75 = 76;
    optional uint64 v76 = 77;
    optional uint64 v77 = 78;
    optional uint64 v78 = 79;
    optional uint64 v79 = 80;
    optional uint64 v80 = 81;
    optional uint64 v81 = 82;
    optional uint64 v82 = 83;
    optional uint64 v83 = 84;
    optional uint64 v84 = 85;
    optional uint64 v85 = 86;
    optional uint64 v86 = 87;
    optional uint64 v87 = 88;
    optional uint64 v88 = 89;
    optional uint64 v89 = 90;
    optional uint64 v90 = 91;
    optional uint64 v91 = 92;
    optional uint64 v92 = 93;
    optional uint64 v93 = 94;
    optional uint64 v94 = 95;
    optional uint64 v95 = 96;
    optional uint64 v96 = 97;
    optional uint64 v97 = 98;
    optional uint64 v98 = 99;
    optional uint64 v99 = 100;
}
